### ISSUE TITLE
[Bug]: transformIgnorePatterns doesn't work with rules_js or rules_jest

### ISSUE THREAD

**Issue by doronrosenberg** [aspect-build/rules_jest#87]
### What happened?

https://jestjs.io/docs/configuration#transformignorepatterns-arraystring

Jest doesn't transform node_modules by default and if you need to transform a dependency you have to use transformignorepatterns in jest config:

```
  transformIgnorePatterns: ["/node_modules/(?!(@rjsf|nanoid|antlr4))"],
```

This doesn't work in rules_js/rules_jest and the files are not transformed, with jest throwing an error.  

I was able to fix this by doing:

```
 transformIgnorePatterns: ["/node_modules/.aspect_rules_js/(?!(@rjsf|nanoid|antlr4))"],
```

but that will break running jest outside of bazel.

### Version

This is using bazel 5.2.0, rules_js 5.8.0 and rules_jest-0.14.3

I see this using rules_jest or running jest-cli using rules_js.

### Any other information?

Might be worth to at least document this as its a fairly common thing to have in jest configs.

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by jbedard** [comment]
See the tip explaining how to do the transform-ignore with pnpm: https://jestjs.io/docs/configuration#transformignorepatterns-arraystring (scroll down a bit to the "tip").

Then replace `.pnpm` with `.aspect_rules_js`. If you're also using pnpm outside bazel you can do `.pnpm|.aspect_rules_js` instead, or if you're using npm or yarn instead of pnpm outside bazel I think you can keep the non-pnpm exclusions for a total of 4?

Since the list of packages needs to be repeated 3-4 times I normally put the list of packages in a variable:
```
const ESM_PKGS = [
  '@rjsf'
  'nanoid'
  'antlr4'
].join('|')

const config = {
  transformIgnorePatterns: [
    // packages within the root pnpm/rules_js package store
    `<rootDir>/node_modules/.(aspect_rules_js|pnpm)/(?!(${ESM_PKGS})@)`,
    // files under a subdir: eg. '/packages/lib-a/'
    `(../)+node_modules/.(aspect_rules_js|pnpm)/(?!(${ESM_PKGS})@)`,
    // packages nested within another
    `node_modules/(?!.aspect_rules_js|.pnpm|${ESM_PKGS})`,
  ],
}
```

I'll close this issue for now but feel free to continue the discussion here if you're still having issues.

**Comment by doronrosenberg** [comment]
For any future folks who run into this, I ended up with:

```
transformIgnorePatterns: ["/node_modules/(?!(.aspect_rules_js|@rjsf|nanoid|antlr4))"],
```
